// Specify properties of an example given to a supervised learning machine, e.g. SVM-STRUCT-SS
// Not using namespace because this header is include in some .c files

#ifndef SVM_STRUCT_SS_EXAMPLE_PARAM_H
#define SVM_STRUCT_SS_EXAMPLE_PARAM_H

#define SVM_STRUCT_SS_EXAMPLE_PARAM_MAX_IMAGE_FILENAME 25
#define SVM_STRUCT_SS_EXAMPLE_PARAM_MAX_IMAGE_WIDTH 150
#define SVM_STRUCT_SS_EXAMPLE_PARAM_MAX_IMAGE_HEIGHT 150

#define SVM_STRUCT_SS_EXAMPLE_PARAM_MAX_N_PIXEL (SVM_STRUCT_SS_EXAMPLE_PARAM_MAX_IMAGE_WIDTH*SVM_STRUCT_SS_EXAMPLE_PARAM_MAX_IMAGE_HEIGHT)
#define SVM_STRUCT_SS_EXAMPLE_PARAM_N_NEIGHBOUR 4 // N-4

#define SVM_STRUCT_SS_EXAMPLE_PARAM_PAIRWISE_POTENTIAL_FUNCTION "Pott"

#endif