LABELS = {	
	'0' : "building",
	'1' : "grass",
	'2' : "tree",
	'3' : "cow",
	'4' : "sheep",
	'5' : "sky",
	'6' : "airplane",
	'7' : "water",
	'8' : "face",
	'9' : "car",
	'10': "bicycle",
	'11': "flower",
	'12': "sign",
	'13': "bird",
	'14': "book",
	'15': "chair",
	'16': "road",
	'17': "cat",
	'18': "dog",
	'19': "body",
	'20': "boat",
	'21': "mountain",
	'22': "horse",
}
